Fixunits
ateucher/rmapshaper pull request #116
Opened 2022-02-13 12:05 UTC by Robinlovelace

2022-02-15 20:39 UTC, Robinlovelace commented
Nudge on this @ateucher if you get a chance please take a look.

2022-02-17 18:55 UTC, ateucher requested changes
Thanks very much @Robinlovelace! I have a suggestion, and one request - would you mind adding a test or two? Apologies I haven't addressed this before now

2022-02-17 18:55 UTC, ateucher commented on R/simplify.R
> +
I think this can be simplified (and be more robust by using `vapply` over `sapply`)

```suggestion
  input_columns_units <- vapply(units, inherits, "units", FUN.VALUE = logical(1))
  if(any(input_columns_units)) {
    msg <- paste0("Coercing these 'units' columns to class numeric:",
                  paste(names(input_columns_units), collapse = ", "))
    warning(msg)
    input[, input_columns_units] <- lapply(input[, input_columns_units, drop = FALSE], 
                                           as.numeric)
  }

```

2022-02-17 19:41 UTC, ateucher commented
Thanks @Robinlovelace - and I actually just realized that it would be great to pull this chunk out into a small function of its own so it can be used in the other `ms_*` functions... and also easier to test. I'm happy to do it if you don't have the time.

2022-02-17 20:01 UTC, Robinlovelace commented
Hitting some issues with your suggested changes, thanks for the offer @ateucher I'll reply in ~5 let's see where I get to and v. grateful if you can finish the job. One more commit incoming...

2022-02-17 20:07 UTC, Robinlovelace commented
OK my PR is done, do with it what you will. Note the `for` loop is I think clearer than the lapply stuff which seemed to have side effects. Also I think `[[` is better than `[` here because `sf` objects are sticky. Many ways of doing these things (the joys of R ... ; ) and happy with anything that works, 3 year issue... nearly fixed, many thanks!

2022-02-17 20:09 UTC, ateucher commented
Thanks again! Right, good call on working around the sticky sf column, I hadn't thought of that. And the `for` loop is just fine!

2022-02-17 20:10 UTC, Robinlovelace commented
Never say final. Didn't save changes to test. See latest commit @ateucher in case you've already just started on this.

2022-02-17 20:18 UTC, ateucher commented
Looking great! Just waiting for the checks to complete - but do you mind removing the new example you added? I don't think it's necessary to test this functionality in the examples, and I'd rather not add `spData` to `Suggests` - which would be best practice if using it an an example.

2022-02-17 20:37 UTC, ateucher reviewed
I think it's pretty much done now, with a couple of other suggestions inline...

Also, the creation of `multipoly_sf` now needs to happen outside [this testthat chunk](https://github.com/ateucher/rmapshaper/pull/116/files#diff-84ef0fe93960aefe286d739505dd6ae177b48e9f5ab1cb49d7f8dd135bfb7f7fR260); on line 258 would be great.

2022-02-17 20:37 UTC, ateucher commented on R/simplify.R
> +    input
This return needs to be after the closing `}` of the `if` statement, otherwise it returns `NULL` when there are no `units` columns.

2022-02-17 20:37 UTC, ateucher commented on tests/testthat/test-simplify.R
> +  multipoly_sf_simple = ms_simplify(multipoly_sf)
can you also wrap this in `expect_warning()`
```suggestion
  expect_warning(multipoly_sf_simple <- ms_simplify(multipoly_sf), "units")
```

2022-02-17 23:42 UTC, ateucher approved these changes

2022-02-17 23:43 UTC, ateucher commented
Thanks again @Robinlovelace! Great to have this finally done :) The CI failures are not due to this PR, so I'll merge it now!

2022-02-17 23:44 UTC, merged